// ── BookChain data.js ───────────────────────────────────────

const BOOKS = [
  {
    id: 1,
    title: "Engineering Mathematics Vol. 1",
    author: "H.K. Dass",
    subject: "Mathematics",
    condition: "like-new",
    emoji: "📐",
    owner: "Ravi V.",
    ownerInitials: "RV",
    ownerColor: "#1D9E75",
    description: "Barely used, no highlights. Perfect for 1st year.",
    campus: "IIT Bengaluru",
  },
  {
    id: 2,
    title: "Introduction to Algorithms",
    author: "CLRS",
    subject: "Computer Science",
    condition: "good",
    emoji: "💻",
    owner: "Priya M.",
    ownerInitials: "PM",
    ownerColor: "#D85A30",
    description: "Some pencil marks in chapter 3. Otherwise great.",
    campus: "BITS Pilani",
  },
  {
    id: 3,
    title: "Principles of Economics",
    author: "N. Gregory Mankiw",
    subject: "Economics",
    condition: "fair",
    emoji: "📊",
    owner: "Sahil J.",
    ownerInitials: "SJ",
    ownerColor: "#378ADD",
    description: "Highlighted throughout but all text readable.",
    campus: "IIT Bengaluru",
  },
  {
    id: 4,
    title: "Computer Networks",
    author: "Andrew Tanenbaum",
    subject: "Computer Science",
    condition: "like-new",
    emoji: "🌐",
    owner: "Ananya K.",
    ownerInitials: "AK",
    ownerColor: "#854F0B",
    description: "Only first two chapters read. Mint condition.",
    campus: "NIT Surathkal",
  },
  {
    id: 5,
    title: "Cell and Molecular Biology",
    author: "Gerald Karp",
    subject: "Biology",
    condition: "good",
    emoji: "🧬",
    owner: "Neha R.",
    ownerInitials: "NR",
    ownerColor: "#634AB7",
    description: "Clean copy, a few sticky notes included.",
    campus: "IISc Bengaluru",
  },
  {
    id: 6,
    title: "University Physics",
    author: "Young & Freedman",
    subject: "Physics",
    condition: "fair",
    emoji: "⚛️",
    owner: "Karan M.",
    ownerInitials: "KM",
    ownerColor: "#D85A30",
    description: "Worn cover but pages are clean.",
    campus: "IIT Bengaluru",
  },
  {
    id: 7,
    title: "Data Structures & Algorithms",
    author: "Mark Allen Weiss",
    subject: "Computer Science",
    condition: "like-new",
    emoji: "🗂️",
    owner: "Tanvi P.",
    ownerInitials: "TP",
    ownerColor: "#1D9E75",
    description: "Purchased last sem, never really used it.",
    campus: "BITS Pilani",
  },
  {
    id: 8,
    title: "Organic Chemistry",
    author: "Morrison & Boyd",
    subject: "Biology",
    condition: "good",
    emoji: "🧪",
    owner: "Arjun S.",
    ownerInitials: "AS",
    ownerColor: "#185FA5",
    description: "Good condition, a few chapters annotated.",
    campus: "IISc Bengaluru",
  },
];

const COVER_COLORS = [
  "#FAEEDA", "#E1F5EE", "#FAECE7", "#E6F1FB",
  "#EAF3DE", "#EEEDFE", "#FCEBEB", "#F1EFE8"
];

const SUBJECTS = ["All", "Computer Science", "Mathematics", "Physics", "Biology", "Economics", "Engineering"];

const CONDITIONS = [
  { value: "",         label: "All"       },
  { value: "like-new", label: "Like New"  },
  { value: "good",     label: "Good"      },
  { value: "fair",     label: "Fair"      },
];
const SWAPS = {
  incoming: [
    {
      id: 101,
      from: "Priya R.",
      fromInitials: "PR",
      fromColor: "#1D9E75",
      theirBook: { emoji: "📘", title: "DBMS – Navathe" },
      myBook:    { emoji: "💻", title: "Algorithms – CLRS" },
      status: "pending",
      steps: [true, true, false, false],
      date: "19 May 2026",
    },
    {
      id: 102,
      from: "Rohan M.",
      fromInitials: "RM",
      fromColor: "#D85A30",
      theirBook: { emoji: "📗", title: "OS – Galvin" },
      myBook:    { emoji: "🌐", title: "Computer Networks" },
      status: "pending",
      steps: [true, false, false, false],
      date: "18 May 2026",
    },
  ],
  outgoing: [
    {
      id: 201,
      from: "Sahil K.",
      fromInitials: "SK",
      fromColor: "#378ADD",
      theirBook: { emoji: "📊", title: "Economics – Mankiw" },
      myBook:    { emoji: "📐", title: "Engg. Maths Vol. 1" },
      status: "active",
      steps: [true, true, true, false],
      date: "17 May 2026",
    },
  ],
  completed: [
    {
      id: 301,
      from: "Neha T.",
      fromInitials: "NT",
      fromColor: "#854F0B",
      theirBook: { emoji: "🧬", title: "Cell Biology – Karp" },
      myBook:    { emoji: "📙", title: "Physics – HC Verma" },
      status: "completed",
      steps: [true, true, true, true],
      date: "10 May 2026",
    },
    {
      id: 302,
      from: "Arun S.",
      fromInitials: "AS",
      fromColor: "#634AB7",
      theirBook: { emoji: "🧪", title: "Organic Chemistry" },
      myBook:    { emoji: "🗂️", title: "Data Structures" },
      status: "completed",
      steps: [true, true, true, true],
      date: "5 May 2026",
    },
  ],
};